"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

// ─────────────────────────────────────────────────────────────────────────────
// SCHEMA NORMALIZERS
// The DB may contain brand kits generated by either the old schema (flat strings)
// or the new schema (rich nested objects). Every helper below handles both.
// ─────────────────────────────────────────────────────────────────────────────

/** If item is a string return it; otherwise pick the first truthy key from it */
function str(item: any, ...keys: string[]): string {
  if (item == null) return "";
  if (typeof item === "string") return item;
  if (typeof item === "number") return String(item);
  for (const k of keys) {
    if (item[k] != null && item[k] !== "") return String(item[k]);
  }
  return "";
}

/** Ensure value is always an array */
function arr(val: any): any[] {
  if (Array.isArray(val)) return val;
  return [];
}

// ── Market analysis normalizers ──────────────────────────────────────────────

function mkMarketSize(m: any): string {
  if (!m) return "";
  // new schema: m.market_sizing.tam
  if (m.market_sizing?.tam) return m.market_sizing.tam;
  // old schema: m.market_size
  return m.market_size ?? "";
}

function mkGrowthRate(m: any): string {
  if (!m) return "";
  return m.market_sizing?.growth_rate ?? m.growth_rate ?? "";
}

function mkTrends(m: any): { trend: string; implication?: string; time_horizon?: string }[] {
  return arr(m?.key_trends).map((t) =>
    typeof t === "string" ? { trend: t } : { trend: t.trend ?? "", implication: t.implication, time_horizon: t.time_horizon }
  );
}

function mkPainPoints(m: any): { pain: string; intensity?: string; emotional_language?: string }[] {
  return arr(m?.pain_points).map((p) =>
    typeof p === "string" ? { pain: p } : { pain: p.pain ?? "", intensity: p.intensity, emotional_language: p.emotional_language }
  );
}

function mkPersona(m: any): any {
  // new schema: target_personas[0]
  if (Array.isArray(m?.target_personas) && m.target_personas.length > 0) return m.target_personas[0];
  // old schema: target_persona (singular)
  return m?.target_persona ?? null;
}

function mkPersonaName(p: any): string {
  if (!p) return "";
  return p.segment_name ?? p.name ?? "";
}

function mkCompetitors(m: any): { name: string; weakness: string; gap: string }[] {
  return arr(m?.competitor_landscape).map((c) => ({
    name: c.name ?? "",
    weakness: c.core_weakness ?? c.weakness ?? "",
    gap: c.exploitable_gap ?? c.opportunity_gap ?? "",
  }));
}

// ── Positioning normalizers ──────────────────────────────────────────────────

function mkBrandNames(p: any): { name: string; rationale?: string }[] {
  return arr(p?.brand_name_suggestions).map((n) =>
    typeof n === "string" ? { name: n } : { name: n.name ?? "", rationale: n.rationale }
  );
}

function mkArchetype(p: any): string {
  if (!p?.brand_archetype) return "";
  if (typeof p.brand_archetype === "string") return p.brand_archetype;
  return p.brand_archetype.primary ?? "";
}

function mkTaglines(p: any): { tagline: string; use_case?: string }[] {
  return arr(p?.tagline_options).map((t) =>
    typeof t === "string" ? { tagline: t } : { tagline: t.tagline ?? "", use_case: t.use_case }
  );
}

function mkColorPalette(p: any): { role: string; hex: string; name: string; desc: string }[] {
  // new schema: visual_identity.color_palette.{primary,secondary,accent,neutral}
  if (p?.visual_identity?.color_palette) {
    const cp = p.visual_identity.color_palette;
    return ["primary", "secondary", "accent", "neutral"].map((role) => ({
      role,
      hex: cp[role]?.hex ?? "",
      name: cp[role]?.name ?? "",
      desc: cp[role]?.psychology ?? cp[role]?.name ?? "",
    }));
  }
  // old schema: color_palette_rationale.{primary,secondary,accent,neutral} = "hex + text"
  if (p?.color_palette_rationale) {
    return Object.entries(p.color_palette_rationale).map(([role, val]: [string, any]) => {
      const text = typeof val === "string" ? val : String(val);
      const hex = text.match(/#[0-9A-Fa-f]{3,6}/)?.[0] ?? "";
      return { role, hex, name: role, desc: text };
    });
  }
  return [];
}

// ── Offer normalizers ────────────────────────────────────────────────────────

function mkGuaranteeMsg(o: any): string {
  return o?.guarantee?.exact_wording ?? o?.guarantee?.messaging ?? "";
}

function mkMargin(o: any): string {
  return o?.core_product?.gross_margin_pct ?? o?.profit_margin_estimate ?? "";
}

function mkPackaging(o: any): { name: string; price: string; features: string[]; popular?: boolean }[] {
  // new: packaging_tiers[].tier_name
  if (Array.isArray(o?.packaging_tiers)) {
    return o.packaging_tiers.map((t: any) => ({
      name: t.tier_name ?? t.tier ?? "",
      price: t.price ?? "",
      features: arr(t.features).map((f: any) => (typeof f === "string" ? f : str(f))),
      popular: t.most_popular,
    }));
  }
  // old: packaging_options[].tier
  return arr(o?.packaging_options).map((t: any) => ({
    name: t.tier ?? "",
    price: t.price ?? "",
    features: arr(t.features).map((f: any) => (typeof f === "string" ? f : str(f))),
  }));
}

// ── Copy normalizers ─────────────────────────────────────────────────────────

function mkHero(c: any): { headline: string; subheadline: string; cta: string } {
  // new: homepage_hero
  if (c?.homepage_hero) {
    return {
      headline: c.homepage_hero.headline ?? "",
      subheadline: c.homepage_hero.subheadline ?? "",
      cta: c.homepage_hero.cta_primary ?? "",
    };
  }
  // old: flat fields
  return {
    headline: c?.hero_headline ?? "",
    subheadline: c?.hero_subheadline ?? "",
    cta: c?.above_fold_cta ?? "",
  };
}

function mkEmailSubjects(c: any): string[] {
  // new: email_sequences.welcome_series[].subject_line
  if (Array.isArray(c?.email_sequences?.welcome_series)) {
    return c.email_sequences.welcome_series.map((e: any) => e.subject_line ?? "").filter(Boolean);
  }
  // old: email_subject_lines
  return arr(c?.email_subject_lines).map((s: any) => (typeof s === "string" ? s : str(s)));
}

function mkUrgencyHooks(c: any): string[] {
  // new: urgency_and_scarcity[].copy
  if (Array.isArray(c?.urgency_and_scarcity)) {
    return c.urgency_and_scarcity.map((u: any) => (typeof u === "string" ? u : u.copy ?? "")).filter(Boolean);
  }
  // old: urgency_scarcity_hooks
  return arr(c?.urgency_scarcity_hooks).map((h: any) => (typeof h === "string" ? h : str(h)));
}

function mkProductDescLong(c: any): string {
  return c?.product_page_copy?.product_description ?? c?.product_description_long ?? "";
}

function mkProductDescShort(c: any): string {
  return c?.product_description_short ?? "";
}

function mkWelcomeEmail(c: any): string {
  if (c?.welcome_email_body) return c.welcome_email_body;
  const first = c?.email_sequences?.welcome_series?.[0];
  return first?.body_outline ?? "";
}

function mkSocialProof(c: any): string[] {
  // new: social_proof.testimonial_prompts OR product_page_copy bullet_benefits
  if (Array.isArray(c?.social_proof_templates)) {
    return c.social_proof_templates.map((s: any) => (typeof s === "string" ? s : str(s)));
  }
  // Try UGC scripts as fallback
  return arr(c?.ad_copy_bank?.ugc_scripts).slice(0, 3).map((s: any) => s.hook ?? str(s));
}

function mkAdHooks(c: any): string[] {
  return arr(c?.ad_copy_bank?.short_hooks).slice(0, 8).map((h: any) => (typeof h === "string" ? h : str(h)));
}

function mkFAQ(c: any): { question: string; answer: string }[] {
  const faq = c?.product_page_copy?.faq_section ?? c?.faq_section ?? [];
  return arr(faq).map((f: any) => ({
    question: f.question ?? "",
    answer: f.answer ?? "",
  }));
}

// ── Ad strategy normalizers ──────────────────────────────────────────────────

function mkChannels(a: any): { channel: string; pct: string; roas: string; rationale: string }[] {
  // old schema: recommended_channels
  if (Array.isArray(a?.recommended_channels)) {
    return a.recommended_channels.map((ch: any) => ({
      channel: ch.channel ?? "",
      pct: ch.budget_allocation_pct != null ? `${ch.budget_allocation_pct}%` : "",
      roas: ch.expected_roas ?? "",
      rationale: ch.rationale ?? "",
    }));
  }
  // new schema: budget_allocation.breakdown
  return arr(a?.budget_allocation?.breakdown).map((b: any) => ({
    channel: b.channel ?? "",
    pct: b.pct_of_budget ?? b.amount ?? "",
    roas: "",
    rationale: b.rationale ?? "",
  }));
}

function mkMetaObjective(a: any): string {
  return a?.meta_ads?.account_structure?.campaign_objective ?? a?.meta_ads?.campaign_objective ?? "";
}

function mkMetaAudience(a: any): string[] {
  // old: meta_ads.audience_targeting
  if (Array.isArray(a?.meta_ads?.audience_targeting)) return a.meta_ads.audience_targeting;
  // new: testing_phase adsets targeting
  return arr(a?.meta_ads?.testing_phase?.adsets).slice(0, 4).map((ad: any) => ad.targeting_details ?? ad.adset_name ?? "");
}

function mkMetaCreatives(a: any): { format: string; hook: string; body: string; cta: string }[] {
  // old: meta_ads.ad_creatives
  if (Array.isArray(a?.meta_ads?.ad_creatives)) {
    return a.meta_ads.ad_creatives.map((ad: any) => ({
      format: ad.format ?? "",
      hook: ad.hook ?? "",
      body: ad.body ?? "",
      cta: ad.cta ?? "",
    }));
  }
  // new: meta_ads.creative_playbook
  return arr(a?.meta_ads?.creative_playbook).slice(0, 4).map((ad: any) => ({
    format: ad.format ?? "",
    hook: ad.hook_type ?? "",
    body: ad.script_outline ?? "",
    cta: ad.best_placement ?? "",
  }));
}

function mkGoogleKeywords(a: any): string[] {
  if (Array.isArray(a?.google_ads?.keywords)) return a.google_ads.keywords;
  return arr(a?.google_ads?.search_campaigns?.keyword_clusters)
    .flatMap((kc: any) => arr(kc.example_keywords))
    .slice(0, 15);
}

function mkGoogleNegativeKeywords(a: any): string[] {
  return arr(a?.google_ads?.negative_keywords ?? a?.google_ads?.search_campaigns?.negative_keywords).slice(0, 12);
}

function mkGoogleCampaignType(a: any): string {
  if (a?.google_ads?.campaign_type) return a.google_ads.campaign_type;
  return arr(a?.google_ads?.recommended_campaign_types).map((t: any) => t.type).join(", ");
}

function mkOrganicPlatforms(a: any): string[] {
  return arr(a?.content_strategy?.organic_platforms ?? a?.tiktok_and_social?.content_formats?.map((f: any) => f.format));
}

function mkContentPillars(a: any): string[] {
  return arr(a?.content_strategy?.content_pillars ?? a?.email_and_sms?.automation_flows?.map((f: any) => f.flow_name));
}

function mkViralHooks(a: any): string[] {
  return arr(a?.content_strategy?.viral_hooks ?? a?.tiktok_and_social?.content_formats?.map((f: any) => f.hook_style));
}

// ── Launch plan normalizers ──────────────────────────────────────────────────

function mkRevenue(l: any): { month1: string; month3: string; month6: string } {
  // old: revenue_projections.{month1,month3,month6}
  if (l?.revenue_projections?.month1) {
    return {
      month1: l.revenue_projections.month1,
      month3: l.revenue_projections.month3 ?? "",
      month6: l.revenue_projections.month6 ?? "",
    };
  }
  // new: financial_model.revenue_projections[] — pick base scenario
  const projs = arr(l?.financial_model?.revenue_projections).filter((p: any) => p.scenario === "base");
  const byMonth: Record<number, string> = {};
  projs.forEach((p: any) => { byMonth[p.month] = p.revenue; });
  return {
    month1: byMonth[1] ?? "",
    month3: byMonth[3] ?? "",
    month6: projs[projs.length - 1]?.revenue ?? "",
  };
}

function mkMilestones(l: any): { week: number; metric: string; tasks: string[] }[] {
  // old: pre_launch.milestones
  if (Array.isArray(l?.pre_launch?.milestones)) {
    return l.pre_launch.milestones.map((ms: any) => ({
      week: ms.week ?? 0,
      metric: ms.success_metric ?? "",
      tasks: arr(ms.tasks).map((t: any) => (typeof t === "string" ? t : str(t))),
    }));
  }
  // new: pre_launch.weeks
  return arr(l?.pre_launch?.weeks).map((w: any) => ({
    week: w.week_number ?? w.week ?? 0,
    metric: w.checkpoint ?? w.theme ?? "",
    tasks: arr(w.tasks).map((t: any) => (typeof t === "string" ? t : t.task ?? str(t))),
  }));
}

function mkDayByDay(l: any): { day: number; focus: string; actions: string[] }[] {
  // old: launch_week.day_by_day
  if (Array.isArray(l?.launch_week?.day_by_day)) {
    return l.launch_week.day_by_day.map((d: any) => ({
      day: d.day ?? 0,
      focus: d.focus ?? "",
      actions: arr(d.actions).map((a: any) => (typeof a === "string" ? a : str(a))),
    }));
  }
  // new: launch_execution.day_by_day
  return arr(l?.launch_execution?.day_by_day).map((d: any) => ({
    day: d.day ?? 0,
    focus: d.theme ?? d.focus ?? "",
    actions: [...arr(d.morning_tasks), ...arr(d.afternoon_tasks)].map((a: any) => (typeof a === "string" ? a : str(a))),
  }));
}

function mkKPIs(l: any): string[] {
  if (Array.isArray(l?.post_launch?.kpis_to_track)) return l.post_launch.kpis_to_track;
  return arr(l?.kpi_dashboard?.daily_metrics).map((m: any) => `${m.metric}: ${m.target}`);
}

function mkGrowthLevers(l: any): string[] {
  if (Array.isArray(l?.post_launch?.month2_3_growth_levers)) return l.post_launch.month2_3_growth_levers;
  return arr(l?.post_launch_optimization?.month2_to_3?.growth_levers).map((g: any) =>
    typeof g === "string" ? g : `${g.lever} (${g.effort} effort)`
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// UI COMPONENTS
// ─────────────────────────────────────────────────────────────────────────────

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base">{title}</CardTitle>
      </CardHeader>
      <CardContent>{children}</CardContent>
    </Card>
  );
}

function TagList({ items }: { items: string[] }) {
  const clean = items.filter(Boolean);
  if (!clean.length) return <p className="text-sm text-muted-foreground italic">—</p>;
  return (
    <div className="flex flex-wrap gap-2">
      {clean.map((item, i) => (
        <Badge key={i} variant="secondary" className="font-normal text-xs">{item}</Badge>
      ))}
    </div>
  );
}

function Kv({ label, value }: { label: string; value?: string }) {
  return (
    <div className="space-y-1">
      <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">{label}</p>
      <p className="text-sm">{value || "—"}</p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN COMPONENT
// ─────────────────────────────────────────────────────────────────────────────

interface BrandKitDisplayProps {
  brandKit: {
    market_analysis: any;
    positioning: any;
    offer: any;
    copy: any;
    ad_strategy: any;
    launch_plan: any;
    generation_time_ms?: number | null;
  };
}

const TABS = [
  { id: "market",      label: "🔍 Market",      title: "Market Analysis" },
  { id: "positioning", label: "🎯 Positioning",  title: "Brand Positioning" },
  { id: "offer",       label: "💎 Offer",        title: "Offer Architecture" },
  { id: "copy",        label: "✍️ Copy",          title: "Conversion Copy" },
  { id: "ads",         label: "📢 Ads",          title: "Ad Strategy" },
  { id: "launch",      label: "🚀 Launch",       title: "Launch Plan" },
];

export default function BrandKitDisplay({ brandKit }: BrandKitDisplayProps) {
  const m = brandKit.market_analysis;
  const p = brandKit.positioning;
  const o = brandKit.offer;
  const c = brandKit.copy;
  const a = brandKit.ad_strategy;
  const l = brandKit.launch_plan;

  const trends    = mkTrends(m);
  const painPts   = mkPainPoints(m);
  const persona   = mkPersona(m);
  const comps     = mkCompetitors(m);
  const brandNames = mkBrandNames(p);
  const taglines  = mkTaglines(p);
  const colors    = mkColorPalette(p);
  const packaging = mkPackaging(o);
  const hero      = mkHero(c);
  const channels  = mkChannels(a);
  const milestones = mkMilestones(l);
  const dayPlan   = mkDayByDay(l);
  const revenue   = mkRevenue(l);

  return (
    <Tabs defaultValue="market">
      <TabsList className="grid grid-cols-3 lg:grid-cols-6 h-auto gap-1 mb-6">
        {TABS.map((t) => (
          <TabsTrigger key={t.id} value={t.id} className="text-xs py-2">
            {t.label}
          </TabsTrigger>
        ))}
      </TabsList>

      {/* ── Tab 1: Market Analysis ─────────────────────────────────────────── */}
      <TabsContent value="market" className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Section title="Market Size">
            <p className="text-sm">{mkMarketSize(m) || "—"}</p>
            <p className="text-sm mt-2 text-muted-foreground">Growth: {mkGrowthRate(m) || "—"}</p>
            <div className="mt-3 flex items-center gap-2">
              <span className="text-xs text-muted-foreground">Market Readiness</span>
              <Badge>{m?.market_readiness_score ?? "—"}/10</Badge>
            </div>
            {m?.executive_summary && (
              <p className="text-xs text-muted-foreground mt-3 leading-relaxed">{m.executive_summary}</p>
            )}
          </Section>

          <Section title="Key Trends">
            <ul className="space-y-2">
              {trends.length ? trends.map((t, i) => (
                <li key={i} className="text-sm">
                  <span className="flex gap-2"><span className="text-muted-foreground shrink-0">→</span><span>{t.trend}</span></span>
                  {t.implication && <p className="text-xs text-muted-foreground mt-0.5 ml-4">{t.implication}</p>}
                </li>
              )) : <p className="text-sm text-muted-foreground italic">—</p>}
            </ul>
          </Section>

          <Section title="Pain Points">
            <ul className="space-y-2">
              {painPts.length ? painPts.map((p, i) => (
                <li key={i} className="text-sm">
                  <span className="flex gap-2 items-start">
                    <span className="text-muted-foreground shrink-0">•</span>
                    <span>{p.pain}</span>
                  </span>
                  {p.emotional_language && (
                    <p className="text-xs italic text-muted-foreground mt-0.5 ml-4">"{p.emotional_language}"</p>
                  )}
                </li>
              )) : <p className="text-sm text-muted-foreground italic">—</p>}
            </ul>
          </Section>
        </div>

        <Section title={`Target Persona${mkPersonaName(persona) ? ` — ${mkPersonaName(persona)}` : ""}`}>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Psychographics</p>
              <TagList items={arr(persona?.psychographics).map((s: any) => (typeof s === "string" ? s : str(s)))} />
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Buying Triggers</p>
              <TagList items={arr(persona?.buying_triggers).map((s: any) => (typeof s === "string" ? s : str(s)))} />
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Objections</p>
              <TagList items={arr(persona?.objections).map((s: any) => (typeof s === "string" ? s : str(s)))} />
            </div>
          </div>
          {persona?.dream_outcome && (
            <div className="mt-4 p-3 bg-primary/5 rounded-lg border border-primary/10">
              <p className="text-xs font-medium text-muted-foreground uppercase mb-1">Dream Outcome</p>
              <p className="text-sm">{persona.dream_outcome}</p>
            </div>
          )}
        </Section>

        <Section title="Competitor Landscape">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {comps.length ? comps.map((comp, i) => (
              <div key={i} className="border rounded-lg p-3 space-y-1">
                <p className="font-semibold text-sm">{comp.name}</p>
                <p className="text-xs text-muted-foreground">Weakness: {comp.weakness}</p>
                <p className="text-xs text-green-600 dark:text-green-400">Gap: {comp.gap}</p>
              </div>
            )) : <p className="text-sm text-muted-foreground italic">—</p>}
          </div>
        </Section>
      </TabsContent>

      {/* ── Tab 2: Positioning ─────────────────────────────────────────────── */}
      <TabsContent value="positioning" className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Section title="Brand Names">
            <div className="flex flex-wrap gap-2">
              {brandNames.length ? brandNames.map((n, i) => (
                <div key={i} className="space-y-0.5">
                  <Badge variant={i === 0 ? "default" : "outline"} className="text-sm px-3 py-1">
                    {i === 0 && "★ "}{n.name}
                  </Badge>
                  {n.rationale && <p className="text-xs text-muted-foreground pl-1">{n.rationale}</p>}
                </div>
              )) : <p className="text-sm text-muted-foreground italic">—</p>}
            </div>
          </Section>
          <Section title="Brand Archetype">
            <p className="text-lg font-semibold">{mkArchetype(p) || "—"}</p>
            {p?.brand_archetype?.archetype_application && (
              <p className="text-xs text-muted-foreground mt-2">{p.brand_archetype.archetype_application}</p>
            )}
            <div className="mt-3">
              <TagList items={arr(p?.brand_personality_traits).map((s: any) => (typeof s === "string" ? s : str(s)))} />
            </div>
          </Section>
        </div>

        <Section title="Positioning Statement">
          <p className="text-sm leading-relaxed italic border-l-4 border-primary pl-4">
            "{p?.positioning_statement || "—"}"
          </p>
        </Section>
        <Section title="Value Proposition">
          <p className="text-sm">{p?.value_proposition || "—"}</p>
        </Section>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Section title="Tone of Voice">
            <TagList items={arr(p?.tone_of_voice).map((s: any) => (typeof s === "string" ? s : str(s)))} />
            {p?.tone_examples?.do_say && (
              <div className="mt-3 space-y-2">
                <p className="text-xs font-medium text-green-600 uppercase">✓ Do say</p>
                {arr(p.tone_examples.do_say).slice(0, 3).map((s: any, i: number) => (
                  <p key={i} className="text-xs text-muted-foreground">"{typeof s === "string" ? s : str(s)}"</p>
                ))}
              </div>
            )}
          </Section>
          <Section title="Tagline Options">
            <ul className="space-y-2">
              {taglines.length ? taglines.map((t, i) => (
                <li key={i} className="space-y-0.5">
                  <p className="text-sm font-medium">"{t.tagline}"</p>
                  {t.use_case && <p className="text-xs text-muted-foreground">{t.use_case}</p>}
                </li>
              )) : <p className="text-sm text-muted-foreground italic">—</p>}
            </ul>
          </Section>
        </div>

        <Section title="Color Palette">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {colors.length ? colors.map((col) => (
              <div key={col.role} className="space-y-1.5">
                {col.hex && (
                  <div className="w-full h-12 rounded-lg border" style={{ backgroundColor: col.hex }} />
                )}
                <p className="text-xs font-semibold capitalize">{col.role}</p>
                <p className="text-xs text-muted-foreground">{col.hex || ""}</p>
                <p className="text-xs text-muted-foreground">{col.desc}</p>
              </div>
            )) : <p className="text-sm text-muted-foreground italic">—</p>}
          </div>
        </Section>

        {p?.differentiation_strategy && (
          <Section title="Differentiation Strategy">
            <p className="text-sm leading-relaxed">{p.differentiation_strategy}</p>
          </Section>
        )}
      </TabsContent>

      {/* ── Tab 3: Offer ───────────────────────────────────────────────────── */}
      <TabsContent value="offer" className="space-y-4">
        <Section title="Core Offer">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-3">
              <Kv label="Product Name"    value={o?.core_product?.name} />
              <Kv label="Price Point"     value={o?.core_product?.price_point} />
              <Kv label="Gross Margin"    value={mkMargin(o)} />
              <Kv label="LTV Estimate"    value={o?.core_product?.ltv_estimate} />
            </div>
            <div className="space-y-3">
              <Kv label="One-Liner"       value={o?.core_product?.one_liner ?? o?.core_product?.description} />
              <Kv label="Price Rationale" value={o?.core_product?.price_psychology ?? o?.core_product?.price_anchoring_rationale} />
            </div>
          </div>
        </Section>

        <Section title="Guarantee">
          <div className="bg-green-50 dark:bg-green-950/20 border border-green-200 dark:border-green-800 rounded-lg p-4">
            <p className="font-semibold text-sm">
              {o?.guarantee?.type}{o?.guarantee?.duration ? ` · ${o.guarantee.duration}` : ""}
            </p>
            <p className="text-sm mt-1 text-muted-foreground">"{mkGuaranteeMsg(o)}"</p>
          </div>
        </Section>

        <Section title="Upsell Stack">
          <div className="space-y-3">
            {arr(o?.upsell_stack).length ? arr(o?.upsell_stack).map((item: any, i: number) => (
              <div key={i} className="flex items-start gap-3 border rounded-lg p-3">
                <Badge variant="outline" className="shrink-0">{i + 1}</Badge>
                <div className="space-y-0.5">
                  <p className="font-semibold text-sm">{item.name} — {item.price}</p>
                  <p className="text-xs text-muted-foreground">When: {item.timing}</p>
                  <p className="text-xs">{item.conversion_hook}</p>
                  {item.expected_take_rate && (
                    <p className="text-xs text-muted-foreground">Take rate: {item.expected_take_rate}</p>
                  )}
                </div>
              </div>
            )) : <p className="text-sm text-muted-foreground italic">—</p>}
          </div>
        </Section>

        <Section title="Packaging Tiers">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {packaging.length ? packaging.map((tier, i) => (
              <div key={i} className={`border rounded-xl p-4 space-y-2 ${tier.popular ? "border-primary ring-1 ring-primary" : ""}`}>
                <div className="flex justify-between items-center">
                  <p className="font-semibold">{tier.name}</p>
                  <Badge>{tier.price}</Badge>
                </div>
                {tier.popular && <Badge className="text-xs w-fit">Most Popular</Badge>}
                <ul className="space-y-1">
                  {tier.features.map((f, j) => (
                    <li key={j} className="text-xs text-muted-foreground flex gap-1"><span>✓</span>{f}</li>
                  ))}
                </ul>
              </div>
            )) : <p className="text-sm text-muted-foreground italic">—</p>}
          </div>
        </Section>
      </TabsContent>

      {/* ── Tab 4: Copy ────────────────────────────────────────────────────── */}
      <TabsContent value="copy" className="space-y-4">
        <Section title="Hero Section">
          <div className="space-y-2 text-center py-4">
            <p className="text-2xl font-bold">{hero.headline || "—"}</p>
            <p className="text-muted-foreground">{hero.subheadline}</p>
            {hero.cta && <Badge className="text-sm px-4 py-1.5">{hero.cta}</Badge>}
          </div>
        </Section>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Section title="Email Subject Lines">
            <ul className="space-y-2">
              {mkEmailSubjects(c).length ? mkEmailSubjects(c).map((s, i) => (
                <li key={i} className="text-sm border-l-2 border-primary/30 pl-3">{s}</li>
              )) : <p className="text-sm text-muted-foreground italic">—</p>}
            </ul>
          </Section>
          <Section title="Urgency / Scarcity Hooks">
            <ul className="space-y-2">
              {mkUrgencyHooks(c).length ? mkUrgencyHooks(c).map((h, i) => (
                <li key={i} className="text-sm border-l-2 border-orange-400/40 pl-3">{h}</li>
              )) : <p className="text-sm text-muted-foreground italic">—</p>}
            </ul>
          </Section>
        </div>

        {mkAdHooks(c).length > 0 && (
          <Section title="Ad Hooks (Meta / TikTok)">
            <ul className="space-y-2">
              {mkAdHooks(c).map((h, i) => (
                <li key={i} className="text-sm border-l-2 border-blue-400/40 pl-3">{h}</li>
              ))}
            </ul>
          </Section>
        )}

        <Section title="Product Description">
          <p className="text-sm leading-relaxed">{mkProductDescLong(c) || "—"}</p>
          {mkProductDescShort(c) && (
            <div className="mt-3 p-3 bg-muted rounded-lg">
              <p className="text-xs text-muted-foreground font-medium mb-1">Short version</p>
              <p className="text-sm">{mkProductDescShort(c)}</p>
            </div>
          )}
        </Section>

        {mkWelcomeEmail(c) && (
          <Section title="Welcome Email">
            <pre className="text-sm leading-relaxed whitespace-pre-wrap font-sans">{mkWelcomeEmail(c)}</pre>
          </Section>
        )}

        {mkSocialProof(c).length > 0 && (
          <Section title="Social Proof Templates">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              {mkSocialProof(c).map((t, i) => (
                <div key={i} className="bg-muted rounded-lg p-3 text-sm italic">"{t}"</div>
              ))}
            </div>
          </Section>
        )}

        {mkFAQ(c).length > 0 && (
          <Section title="FAQ Section">
            <div className="space-y-3">
              {mkFAQ(c).map((faq, i) => (
                <div key={i}>
                  <p className="text-sm font-semibold">Q: {faq.question}</p>
                  <p className="text-sm text-muted-foreground mt-0.5">A: {faq.answer}</p>
                </div>
              ))}
            </div>
          </Section>
        )}
      </TabsContent>

      {/* ── Tab 5: Ads ─────────────────────────────────────────────────────── */}
      <TabsContent value="ads" className="space-y-4">
        {channels.length > 0 && (
          <Section title="Channel Mix">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {channels.map((ch, i) => (
                <div key={i} className="border rounded-lg p-3 space-y-1">
                  <div className="flex justify-between flex-wrap gap-2">
                    <p className="font-semibold text-sm">{ch.channel}</p>
                    <div className="flex gap-2">
                      {ch.pct && <Badge variant="outline">{ch.pct} budget</Badge>}
                      {ch.roas && <Badge variant="secondary">{ch.roas} ROAS</Badge>}
                    </div>
                  </div>
                  <p className="text-xs text-muted-foreground">{ch.rationale}</p>
                </div>
              ))}
            </div>
          </Section>
        )}

        <Section title="Meta Ads">
          <div className="space-y-4">
            <div className="flex gap-4 flex-wrap">
              <Kv label="Objective" value={mkMetaObjective(a)} />
              {(a?.meta_ads?.lookalike_seed ?? a?.meta_ads?.account_structure?.scaling_trigger) && (
                <Kv label="Scaling Trigger"
                  value={a?.meta_ads?.account_structure?.scaling_trigger ?? a?.meta_ads?.lookalike_seed} />
              )}
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Audience / Targeting</p>
              <TagList items={mkMetaAudience(a)} />
            </div>
            <div className="space-y-3">
              <p className="text-xs font-medium text-muted-foreground uppercase">Ad Creatives</p>
              {mkMetaCreatives(a).length ? mkMetaCreatives(a).map((ad, i) => (
                <div key={i} className="border rounded-lg p-3 space-y-1.5">
                  <Badge variant="outline">{ad.format}</Badge>
                  <p className="text-sm font-semibold">{ad.hook}</p>
                  <p className="text-sm text-muted-foreground">{ad.body}</p>
                  {ad.cta && <p className="text-sm font-medium text-primary">CTA / Placement: {ad.cta}</p>}
                </div>
              )) : <p className="text-sm text-muted-foreground italic">—</p>}
            </div>
          </div>
        </Section>

        <Section title="Google Ads">
          <div className="space-y-3">
            <Kv label="Campaign Type" value={mkGoogleCampaignType(a)} />
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Target Keywords</p>
              <TagList items={mkGoogleKeywords(a)} />
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Negative Keywords</p>
              <TagList items={mkGoogleNegativeKeywords(a)} />
            </div>
          </div>
        </Section>

        <Section title="Organic Content Strategy">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Platforms</p>
              <TagList items={mkOrganicPlatforms(a)} />
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Content Pillars</p>
              <TagList items={mkContentPillars(a)} />
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase mb-2">Viral Hooks</p>
              <ul className="space-y-1">
                {mkViralHooks(a).map((h, i) => (
                  <li key={i} className="text-xs">{h}</li>
                ))}
              </ul>
            </div>
          </div>
        </Section>
      </TabsContent>

      {/* ── Tab 6: Launch Plan ─────────────────────────────────────────────── */}
      <TabsContent value="launch" className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            { label: "Month 1", value: revenue.month1 },
            { label: "Month 3", value: revenue.month3 },
            { label: "Month 6", value: revenue.month6 },
          ].map(({ label, value }) => (
            <Section key={label} title={`Revenue — ${label}`}>
              <p className="text-2xl font-bold text-primary">{value || "—"}</p>
            </Section>
          ))}
        </div>

        <Section title="Pre-Launch Phase">
          <div className="space-y-3">
            {milestones.length ? milestones.map((ms, i) => (
              <div key={i} className="border rounded-lg p-3">
                <p className="text-sm font-semibold mb-1">Week {ms.week} — {ms.metric}</p>
                <ul className="space-y-0.5">
                  {ms.tasks.map((task, j) => (
                    <li key={j} className="text-xs text-muted-foreground flex gap-1.5">
                      <span className="text-primary shrink-0">✓</span>{task}
                    </li>
                  ))}
                </ul>
              </div>
            )) : <p className="text-sm text-muted-foreground italic">—</p>}
          </div>
        </Section>

        <Section title="Launch Week — Day by Day">
          <div className="space-y-3">
            {dayPlan.length ? dayPlan.map((day, i) => (
              <div key={i} className="flex gap-3">
                <div className="w-16 shrink-0">
                  <Badge variant="outline" className="w-full justify-center">Day {day.day}</Badge>
                </div>
                <div>
                  <p className="text-sm font-semibold">{day.focus}</p>
                  <ul className="mt-1 space-y-0.5">
                    {day.actions.map((action, j) => (
                      <li key={j} className="text-xs text-muted-foreground">→ {action}</li>
                    ))}
                  </ul>
                </div>
              </div>
            )) : <p className="text-sm text-muted-foreground italic">—</p>}
          </div>
        </Section>

        <Section title="KPIs to Track">
          <TagList items={mkKPIs(l)} />
        </Section>

        <Section title="Month 2–3 Growth Levers">
          <ul className="space-y-1.5">
            {mkGrowthLevers(l).length ? mkGrowthLevers(l).map((lever, i) => (
              <li key={i} className="text-sm flex gap-2">
                <span className="text-primary font-bold shrink-0">→</span>{lever}
              </li>
            )) : <p className="text-sm text-muted-foreground italic">—</p>}
          </ul>
        </Section>
      </TabsContent>
    </Tabs>
  );
}
