// Auto-generated by: npm run db:types
// You can also run: npx supabase gen types typescript --linked > types/database.ts

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
        };
        Update: {
          full_name?: string | null;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          status: string;
          price_id: string;
          quantity: number;
          cancel_at_period_end: boolean;
          current_period_start: string | null;
          current_period_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          status: string;
          price_id: string;
          quantity?: number;
          cancel_at_period_end?: boolean;
          current_period_start?: string | null;
          current_period_end?: string | null;
        };
        Update: {
          status?: string;
          price_id?: string;
          quantity?: number;
          cancel_at_period_end?: boolean;
          current_period_start?: string | null;
          current_period_end?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          product_idea: string;
          niche: string;
          target_audience: string;
          budget_range: string | null;
          competitors: string[] | null;
          unique_selling_point: string | null;
          status: "draft" | "generating" | "complete" | "failed";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          name: string;
          product_idea: string;
          niche: string;
          target_audience: string;
          budget_range?: string | null;
          competitors?: string[] | null;
          unique_selling_point?: string | null;
          status?: string;
        };
        Update: {
          name?: string;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "projects_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      brand_kits: {
        Row: {
          id: string;
          project_id: string;
          user_id: string;
          market_analysis: Json | null;
          positioning: Json | null;
          offer: Json | null;
          copy: Json | null;
          ad_strategy: Json | null;
          launch_plan: Json | null;
          generation_time_ms: number | null;
          model_version: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          project_id: string;
          user_id: string;
          market_analysis?: Json | null;
          positioning?: Json | null;
          offer?: Json | null;
          copy?: Json | null;
          ad_strategy?: Json | null;
          launch_plan?: Json | null;
          generation_time_ms?: number | null;
          model_version?: string | null;
        };
        Update: {
          market_analysis?: Json | null;
          positioning?: Json | null;
          offer?: Json | null;
          copy?: Json | null;
          ad_strategy?: Json | null;
          launch_plan?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: "brand_kits_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: true;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "brand_kits_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
